Pr/fixing whisper bug and updating build instructions
Amaan1234567/KoolIntelligence pull request #22
Opened 2024-10-08 14:49 UTC by Amaan1234567

fixed bugs where it wouldnt compile cpu version when no GPU was detected, updated build instructions to add openvino installation and formmated all files edited with clang format

Checklist(to mark the completed tasks, replace the space inside the brackets with an x):
- [ ] Are the variable and function named correctly. Example: ```myNewVariable```
- [ ] Are the class and structs named correctly. Example: ```MyNewClass```
- [ ] Are the comments clear and concise.
- [ ] Is the documentation updated.
- [ ] There are no new warnings than before*.
- [ ] Are the logs used correctly. Only logs are allowed. No print statements.

*The only reason new warnings may be allowed is if the code that produces the warnings are from third party code that we cannot modify.(Example: Qt, KDE Frameworks, git submodules etc.)

2024-10-09 05:30 UTC, RahulVadhyar requested changes
openvino is showing warning/error in gh actions. I don't think it is getting compiled properly. see that once

2024-10-14 04:05 UTC, RahulVadhyar requested changes
The cmake hack is not getting merged.

2024-10-14 04:05 UTC, RahulVadhyar commented on src/ui/app.cpp
> +    LOG_INFO("app", this->model_api_instance->transcriptionService());
turn this off as it messes with the UI

2024-10-14 04:05 UTC, RahulVadhyar commented on src/model_backend/model_api.hpp
> +                 "You are a helpful AI assistant, who is good at solving the user's queries be it related to coding, general knowledge or anything else a "
make this const so that its purpose is clear

2024-10-14 04:05 UTC, RahulVadhyar commented on src/model_backend/thirdparty/CMakeLists.txt
this is not needed as the whisper.cpp cmake does all this.

2024-10-14 16:37 UTC, RahulVadhyar approved these changes

2024-10-14 16:39 UTC, RahulVadhyar commented
please squash and merge @shrenisc

2024-10-15 05:15 UTC, shrenisc approved these changes
approved.

2024-10-15 05:16 UTC, merged